### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by yashrajbharti**
Brownie points- 
•Responsive
• JavaScript
• jQuery
• canvas

Besides this I made a side pop-up notification that we can minimize ... It's on the about page when we click "Learn More"

There is a carousel at the home page.
The Starbucks logo when clicks lands us to home.

A coffee cup with some steam animation is made... Also there's a custom scroll bar.

The coffee cup when hover shows "click to buy coffee" and if clicked lands us to a website.

### CODE REVIEW

**Comment by shivanshs9** [comment]
Try to introduce your pull request by writing some description or anything.

**Comment by yashrajbharti** [comment]
Brownie points- 
•Responsive
• JavaScript
• jQuery
• canvas

Besides this I made a side pop-up notification that we can minimize ... It's on the about page when we click "Learn More"

There is a carousel at the home page.
The Starbucks logo when clicks lands us to home.

A coffee cup with some steam animation is made... Also there's a custom scroll bar.

The coffee cup when hover shows "click to buy coffee" and if clicked lands us to a website.

**Comment by yashrajbharti** [comment]
I did the description... Rest can be seen by opening the index.html on a browser
https://yashrajbharti.github.io/coffee/
Here is the exact site link...

**Comment by yashrajbharti** [comment]
The nav bar is too a collapsible one...

**Comment by yashrajbharti** [comment]
The README.md  has been created now :octocat: ☕️

**Pull request merged**
